/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Herramientas;

import Tablas.Producto;
import Tablas.Usuario;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class PanelProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelProducto
     */
    private Producto producto;
    private int cantidad;
    
    
    
    public PanelProducto() {
        initComponents();
        this.cantidad = 0;
        //this.producto = new Producto(5, "Producto ejemplo", "Es un producto de ejemplo","/img/usuario.png" );
        this.labelNombre.setText("Producto ejemplo");
        this.labelDescripcion.setText("Es un producto de ejemplo");
        this.labelPrecio.setText("5,00€");
        
        
        ImageIcon icono = new ImageIcon(getClass().getResource("/img/usuario.png"));
        Image img = icono.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
        icono = new ImageIcon(img);
        
        this.labelImg.setIcon(icono);
        this.labelImg.revalidate();
        this.labelImg.repaint();
        
        
    }
 
    public PanelProducto(Producto producto) {  
        initComponents();
        this.cantidad = 0;
        this.producto = producto;
        this.labelNombre.setText(producto.getNombre());
        this.labelNombre.repaint();
        this.labelDescripcion.setText(producto.getDescripcion());
        this.labelDescripcion.repaint();
        this.labelPrecio.setText(producto.getPrecio()+"€");
        this.labelPrecio.repaint();
        this.labelImg.removeAll();
        Image img = producto.devolverImagen().getImage().getScaledInstance(70, 70,Image.SCALE_SMOOTH);
        this.labelImg.setIcon(new ImageIcon(img));
        this.labelImg.revalidate();
        this.labelImg.repaint();
        lableCantidad.setText(cantidad +"");
        
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
        this.lableCantidad.setText(cantidad+"");
    }
    
    
    

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelImg = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        btnMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        lableCantidad = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        setToolTipText("");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 0));
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("nombre");

        labelPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPrecio.setForeground(new java.awt.Color(255, 255, 0));
        labelPrecio.setText("precio");

        labelDescripcion.setForeground(new java.awt.Color(255, 255, 0));
        labelDescripcion.setText("Descripcion");
        labelDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnMas.setBackground(new java.awt.Color(255, 255, 0));
        btnMas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(255, 255, 0));
        btnMenos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        lableCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lableCantidad.setForeground(new java.awt.Color(255, 255, 0));
        lableCantidad.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMenos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lableCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMas)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMas)
                            .addComponent(btnMenos)
                            .addComponent(lableCantidad))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        this.cantidad++;
        this.lableCantidad.setText(cantidad+"");
        this.lableCantidad.repaint();
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        if(cantidad >0){
            this.cantidad--;
            this.lableCantidad.setText(cantidad+"");
            this.lableCantidad.repaint();
        }
    }//GEN-LAST:event_btnMenosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelImg;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel lableCantidad;
    // End of variables declaration//GEN-END:variables
}
