/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.Principal;

import Tablas.Usuario;
import Pantallas.Principal.Paneles.PanelCambiarUser;
import Pantallas.Principal.Paneles.PanelContacto;
import Pantallas.Principal.Paneles.PanelReservas2;

import Pantallas.Principal.Paneles.PanelTienda2;
import Pantallas.Principal.Paneles.Principal;
import Pantallas.login.Login;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.plaf.FileChooserUI;
import javax.swing.JOptionPane;
import logica.Main;
import logica.Tienda;


/**
 *
 * @author 2DAM
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    
    private static Usuario user;
    
    public PantallaPrincipal() {
        initComponents();
    }
    public PantallaPrincipal(Usuario u) throws IOException{
        initComponents();
        this.user = u;
        System.out.println("Texto de ejemplo");
        iniciaruser();
        pintarBtns();
        CambiaPanel.removeAll();
        Principal aux = new Principal();
        aux.setSize(CambiaPanel.getSize());
        CambiaPanel.add(aux);
        CambiaPanel.revalidate();
        CambiaPanel.repaint();
       
    }
    public static Usuario getUser(){
        return PantallaPrincipal.user;
    }
    public void pintarBtns(){
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/IMG/Camara.jpg"));
        ImageIcon iconoEscalado1 = escalarImagen(icono1, btnCambiarImagen.getWidth(), btnCambiarImagen.getHeight());
        btnCambiarImagen.setIcon(iconoEscalado1);
        btnCambiarImagen.revalidate();
        btnCambiarImagen.repaint();
        
        ImageIcon icono2 = new ImageIcon(getClass().getResource("/IMG/Opciones.png"));
        ImageIcon iconoEscalado2 = escalarImagen(icono2, btnOpciones.getWidth(), btnOpciones.getHeight());
        btnOpciones.setIcon(iconoEscalado2);
        btnOpciones.revalidate();
        btnOpciones.repaint();
    }
    
    
    public  void iniciaruser() throws IOException{
        ImageIcon icono = user.devolverImagen(user.getFoto());
        ImageIcon iconoEscalado = escalarImagen(icono, Img.getWidth(), Img.getHeight());
        UserName.setText(user.getNombre());
        Img.setIcon(iconoEscalado);
        Img.revalidate();
        Img.repaint();
        
    }
    
    private ImageIcon escalarImagen(ImageIcon icono, int ancho, int alto) {
    Image imagenOriginal = icono.getImage();
    int nuevaAnchura, nuevaAltura;

    if (imagenOriginal.getWidth(null) > imagenOriginal.getHeight(null)) {
        nuevaAnchura = ancho;
        nuevaAltura = -1;
    } else {
        nuevaAnchura = -1;
        nuevaAltura = alto;
    }

    Image imagenEscalada = imagenOriginal.getScaledInstance(nuevaAnchura, nuevaAltura, Image.SCALE_SMOOTH);

    return new ImageIcon(imagenEscalada);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        UserPanel = new javax.swing.JPanel();
        Img = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        btnCambiarImagen = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        botonera = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        btnContacto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        CambiaPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 102, 0));
        jPanel5.setForeground(new java.awt.Color(255, 255, 153));

        UserPanel.setBackground(new java.awt.Color(0, 0, 0));

        UserName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 0));
        UserName.setText("Usuario");

        btnCambiarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarImagenActionPerformed(evt);
            }
        });

        btnOpciones.setPreferredSize(new java.awt.Dimension(50, 50));
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addComponent(Img, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCambiarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Img, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnCambiarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(UserName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 0, 0));

        botonera.setBackground(new java.awt.Color(255, 255, 0));

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 0));
        btnHome.setText("Inicio");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnReservar.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(255, 255, 0));
        btnReservar.setText("Encargos");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnComprar.setBackground(new java.awt.Color(0, 0, 0));
        btnComprar.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 0));
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnContacto.setBackground(new java.awt.Color(0, 0, 0));
        btnContacto.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnContacto.setForeground(new java.awt.Color(255, 255, 0));
        btnContacto.setText("Contacto");
        btnContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoneraLayout = new javax.swing.GroupLayout(botonera);
        botonera.setLayout(botoneraLayout);
        botoneraLayout.setHorizontalGroup(
            botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoneraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        botoneraLayout.setVerticalGroup(
            botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoneraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jScrollPane1.setViewportView(botonera);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        CambiaPanel.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout CambiaPanelLayout = new javax.swing.GroupLayout(CambiaPanel);
        CambiaPanel.setLayout(CambiaPanelLayout);
        CambiaPanelLayout.setHorizontalGroup(
            CambiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        CambiaPanelLayout.setVerticalGroup(
            CambiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CambiaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CambiaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        CambiaPanel.removeAll();
        Principal aux = new Principal();
        aux.setSize(CambiaPanel.getSize());
        CambiaPanel.add(aux);
        CambiaPanel.revalidate();
        CambiaPanel.repaint();
        try {
            iniciaruser();
        } catch (IOException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        CambiaPanel.removeAll();
        PanelReservas2 aux = new PanelReservas2();
        aux.setSize(CambiaPanel.getSize());
        CambiaPanel.add(aux);
        CambiaPanel.revalidate();
        CambiaPanel.repaint();
        try {
            iniciaruser();
        } catch (IOException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        CambiaPanel.removeAll();
        PanelTienda2 aux = new PanelTienda2();
        aux.setSize(CambiaPanel.getSize());
        CambiaPanel.add(aux);
        CambiaPanel.revalidate();
        CambiaPanel.repaint();
        try {
            iniciaruser();
        } catch (IOException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactoActionPerformed
        CambiaPanel.removeAll();
        PanelContacto aux = new PanelContacto();
        aux.setSize(CambiaPanel.getSize());
        CambiaPanel.add(aux);
        CambiaPanel.revalidate();
        CambiaPanel.repaint();
        try {
            iniciaruser();
        } catch (IOException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnContactoActionPerformed

    private void btnCambiarImagenActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Buscar icono");
        fc.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File file) {
                return file.isDirectory() || file.getName().toLowerCase().endsWith(".jpg") || file.getName().toLowerCase().endsWith(".png");
            }
            @Override
            public String getDescription() {
                return "Archivos de Imagen (*.jpg, *.png)";
            }
        });
        int res = fc.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            JOptionPane.showMessageDialog(this, "Por favor, asegúrese de actualizar la carpeta IMG.", "Actualizar carpeta", JOptionPane.INFORMATION_MESSAGE);
            ImageIcon icono = new ImageIcon(fc.getSelectedFile().getAbsolutePath());
            Main.shop.cambiarImagenUser(user, Tienda.guardarEnIMG(fc.getSelectedFile().getAbsolutePath(), user.getNombre()));
            try {
                iniciaruser();
            } catch (IOException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
        CambiaPanel.removeAll();
        PanelCambiarUser aux = new PanelCambiarUser(user);
        aux.setSize(CambiaPanel.getSize());
        CambiaPanel.add(aux);
        UserName.setText(user.getNombre());
        CambiaPanel.revalidate();
        CambiaPanel.repaint();
        try {
            iniciaruser();
        } catch (IOException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOpcionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       Login l = new Login();
       this.dispose();
       l.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CambiaPanel;
    private javax.swing.JLabel Img;
    private javax.swing.JLabel UserName;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JPanel botonera;
    private javax.swing.JButton btnCambiarImagen;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnContacto;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
