package Tablas;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

// default package
// Generated 28 feb 2024, 16:15:03 by Hibernate Tools 6.3.1.Final

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura")
public class Factura implements java.io.Serializable {
	@Id
	@Column(name = "id_fac")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idFac;
	@ManyToOne
	@JoinColumn(name = "id_com")
	private Compras compras;
	@ManyToOne
	@JoinColumn(name = "id_pro")
	private Producto producto;
	@Column
	private Integer cantidad;

	public Factura() {
	}

	public Factura(Compras compras, Producto producto, Integer cantidad) {
		this.compras = compras;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	public Integer getIdFac() {
		return this.idFac;
	}

	public void setIdFac(Integer idFac) {
		this.idFac = idFac;
	}

	public Compras getCompras() {
		return this.compras;
	}

	public void setCompras(Compras compras) {
		this.compras = compras;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
