package Tablas;

// default package
// Generated 28 feb 2024, 16:15:03 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import javax.swing.ImageIcon;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto")
public class Producto implements java.io.Serializable {
	
	@Id
	@Column(name ="id_pro")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idPro;
	@Column
	private String nombre;
	@Column
	private String descripcion;
	@Column
	private Float precio;
	@Column
	private String img;
	@OneToMany(mappedBy = "producto")
	private Set<Factura> facturas = new HashSet(0);

	public Producto() {
	}

	public Producto(String nombre, String descripcion, Float precio, String img) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.precio = precio;
		this.img = img;
	}

	public Integer getIdPro() {
		return this.idPro;
	}

	public void setIdPro(Integer idPro) {
		this.idPro = idPro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}
        public ImageIcon devolverImagen() {
		return new ImageIcon(getClass().getResource(this.getImg()));
	}
        public String[] toArrayString(){
            return new String[] {this.getIdPro()+"", this.getNombre(), this.getDescripcion(), this.getPrecio()+"", this.getImg()};       
        }
        public String[] toArrayString(int cantidad){
            return new String[] {this.getIdPro()+"", this.getNombre(), this.getDescripcion(), this.getPrecio()+"", cantidad+""};
        }
}
