package Tablas;

// default package
// Generated 28 feb 2024, 16:15:03 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name = "reserva")
public class Reserva implements java.io.Serializable {
	
	@Id
	@Column(name = "id_res")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idRes;
	@ManyToOne
	@JoinColumn (name = "id_use")
	private Usuario usuario;
	@Column
	private Date falta;
	@Column
	private Date fbaja;
	@Column
	private String tipo;

	public Reserva() {
	}

	public Reserva(Usuario usuario, Date falta, Date fbaja, String tipo) {
		this.usuario = usuario;
		this.falta = falta;
		this.fbaja = fbaja;
		this.tipo = tipo;
	}

	public Integer getIdRes() {
		return this.idRes;
	}

	public void setIdRes(Integer idRes) {
		this.idRes = idRes;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFalta() {
		return this.falta;
	}

	public void setFalta(Date falta) {
		this.falta = falta;
	}

	public Date getFbaja() {
		return this.fbaja;
	}

	public void setFbaja(Date fbaja) {
		this.fbaja = fbaja;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	public static String toStringFecha(Date d){
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String date = sdf.format(d);
        return date;
    }
    public static Date stringToDate(String s) throws ParseException{
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date fechaBase = sdf.parse(s);
        java.sql.Date d =  new java.sql.Date(fechaBase.getTime());
        return d;
    }

	public String[] toArrayString(){
		String id = "" + this.getIdRes();
        String[] arrayString ={id ,this.getTipo(), this.getUsuario().getNombre(), toStringFecha(this.falta), toStringFecha(this.fbaja)};
        return arrayString;
    }
}
