package Tablas;

// default package
// Generated 28 feb 2024, 16:15:03 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.swing.ImageIcon;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name ="usuario")
public class Usuario implements java.io.Serializable {
	@Id
	@Column(name ="id_use")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idUse;
	@Column
	private String nombre;
	@Column
	private String contraseña;
	@Column
	private String correo;
	@Column
	private String foto;
	@Column
	private Boolean admin;
	@OneToMany(mappedBy = "usuario")
	private Set<Reserva> reservas = new HashSet(0);
	@OneToMany(mappedBy = "usuario")
	private Set<Compras> comprases = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String nombre, String contraseña, String correo, 
			String foto, Boolean admin) {
		this.nombre = nombre;
		this.contraseña = contraseña;
		this.correo = correo;
		this.foto = foto;
		this.admin = admin;
	}

	public Integer getIdUse() {
		return this.idUse;
	}

	public void setIdUse(Integer idUse) {
		this.idUse = idUse;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(String contraseña) {
		this.contraseña = contraseña;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public Boolean getAdmin() {
		return this.admin;
	}

	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}

	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}

	public Set getComprases() {
		return this.comprases;
	}

	public void setComprases(Set comprases) {
		this.comprases = comprases;
	}
	
	public ImageIcon devolverImagen(String url) {
		return new ImageIcon(getClass().getResource(url));
	}
	
	
	

}
