/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pantallas.Principal.Paneles;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;

import Tablas.Producto;
import Tablas.ProductoDao;

import Tablas.Usuario;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import logica.Main;
import logica.Tienda;
/**
 *
 * @author LUIS MIGUEL
 */
public class AdminProductos extends javax.swing.JDialog {
	
    private JList<Producto> productList;
    private String ruta;
    private ImageIcon img;
    private Producto producto;
    private  TableRowSorter <DefaultTableModel> sorter;


    /**
     * Creates new form AdminProductos
     */
    
    public AdminProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        formatearTabla();
        actualizarTabla();
        ruta = "";
    }
    
    public void formatearTabla(){
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.setColumnIdentifiers(new String[] {"id", "Nombre", "Descripcion", "precio", "img"});
        tablaProductos.setModel(tabla);
        sorter= new TableRowSorter<DefaultTableModel>(tabla);
        productList = new JList<Producto>();
    }
    
    public void actualizarTabla(){
        SwingUtilities.invokeLater(() -> {
            DefaultTableModel tabla = (DefaultTableModel) tablaProductos.getModel();
            tabla.setRowCount(0);
            for(Producto p: Main.shop.devolverTodosProductos()){
                tabla.addRow(p.toArrayString());   
            }
        });
        tablaProductos.setRowSorter(sorter);
        List <RowSorter.SortKey> sorkeys = new ArrayList();
        sorkeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
        sorter.setSortKeys(sorkeys);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSeleccionar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ImgLabel = new javax.swing.JLabel();
        btnImg = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        tfprecio = new javax.swing.JTextField();
        btnCambiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btnNew.setBackground(new java.awt.Color(255, 255, 0));
        btnNew.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNew.setForeground(new java.awt.Color(0, 0, 0));
        btnNew.setText("Nuevo producto");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSeleccionar1.setBackground(new java.awt.Color(255, 255, 0));
        btnSeleccionar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSeleccionar1.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionar1.setText("Seleccionar");
        btnSeleccionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnSeleccionar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(btnNew)
                .addGap(268, 268, 268))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSeleccionar1))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        ImgLabel.setBackground(new java.awt.Color(255, 255, 255));

        btnImg.setBackground(new java.awt.Color(255, 255, 0));
        btnImg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnImg.setForeground(new java.awt.Color(0, 0, 0));
        btnImg.setText("Seleccionar Img");
        btnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgActionPerformed(evt);
            }
        });

        tfNombre.setBackground(new java.awt.Color(255, 255, 102));
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfDescripcion.setBackground(new java.awt.Color(255, 255, 102));
        tfDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescripcionActionPerformed(evt);
            }
        });

        tfprecio.setBackground(new java.awt.Color(255, 255, 102));
        tfprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfprecioActionPerformed(evt);
            }
        });

        btnCambiar.setBackground(new java.awt.Color(255, 255, 0));
        btnCambiar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCambiar.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiar.setText("Aplicar cambios");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Descripcion");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Precio");

        lblInfo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 255, 51));
        lblInfo.setText("Nuevo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(ImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImg)
                .addGap(57, 57, 57))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)))
                .addGap(120, 120, 120))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCambiar)
                .addGap(182, 182, 182))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(344, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(128, 128, 128)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnImg))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCambiar)
                            .addComponent(lblInfo))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfprecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(99, 99, 99))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(jLabel2)
                    .addContainerGap(246, Short.MAX_VALUE)))
        );

        tablaProductos.setBackground(new java.awt.Color(0, 0, 0));
        tablaProductos.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tablaProductos.setForeground(new java.awt.Color(204, 204, 0));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        int pos = productList.getSelectedIndex();
        int conv = tablaProductos.convertRowIndexToModel(pos);
        System.out.println("Mira puto");
        
    }


    private void btnImgActionPerformed(java.awt.event.ActionEvent evt) {                                       
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Buscar icono");
        fc.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File file) {
                return file.isDirectory() || file.getName().toLowerCase().endsWith(".jpg") || file.getName().toLowerCase().endsWith(".png");
            }

            @Override
            public String getDescription() {
                return "Archivos de Imagen (*.jpg, *.png)";
            }
        });
        int res =fc.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            ImageIcon icono = new ImageIcon(fc.getSelectedFile().getAbsolutePath());
            ruta = fc.getSelectedFile().getAbsolutePath();
            System.out.println(ruta);
            img = icono;
            ImgLabel.setText(fc.getSelectedFile().getAbsolutePath());
        }
        
        
    }             



    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescripcionActionPerformed

    private void tfprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfprecioActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
        producto = null;
        tfNombre.setText("");
        tfDescripcion.setText("");
        tfprecio.setText("");
        ImgLabel.setText("");
        lblInfo.setText("Nuevo");
    }
    private boolean comprobarCampos(){
        return (tfNombre.getText().equals("") != true && tfDescripcion.getText().equals("") != true && tfprecio.getText().equals("") != true);
    }
    
    private void resetearCampos(){
        ruta = "";
        tfDescripcion.setText("");
        tfNombre.setText("");
        tfprecio.setText("");
        producto = null;
    }
    

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        if (comprobarCampos()) {
            String nombre = tfNombre.getText();
            String descripcion = tfDescripcion.getText();
            float precio = Float.parseFloat(tfprecio.getText());
        if(producto == null){
            if(ruta.equals("")){
                Producto aux = new Producto(nombre, descripcion, precio, "/IMG/6r.jpg");
                new ProductoDao().createRecord(aux);
            }else{
                
                Producto aux = new Producto(nombre, descripcion, precio, Tienda.guardarEnIMG(ruta, nombre));
                new ProductoDao().createRecord(aux);
            }
        }else{
            if(ruta.equals("")){
                Producto aux = new Producto(nombre, descripcion, precio, producto.getImg());
                new ProductoDao().updateRecord(aux, producto.getIdPro());
            }else{
                Producto aux = new Producto(nombre, descripcion, precio, Tienda.guardarEnIMG(ruta, nombre));
                new ProductoDao().updateRecord(aux, producto.getIdPro());
            }
        }
        JOptionPane.showMessageDialog(this, "Por favor, asegúrese de actualizar la carpeta IMG.", "Actualizar carpeta", JOptionPane.INFORMATION_MESSAGE);
        } else {
        	System.out.println("error(falta un o varios campos sin informacion)");
        }        // TODO add your handling code here:
        resetearCampos();
        actualizarTabla();
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnSeleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar1ActionPerformed
        int pos = tablaProductos.getSelectedRow();
        int conv = tablaProductos.convertRowIndexToModel(pos);
        if(pos != -1){
            DefaultTableModel tabla = (DefaultTableModel) tablaProductos.getModel();
            int id = Integer.parseInt(tablaProductos.getModel().getValueAt(conv, 0)+"");
            producto = new ProductoDao().readRecord(id);
            tfNombre.setText(producto.getNombre());
            tfDescripcion.setText(producto.getDescripcion());
            tfprecio.setText(producto.getPrecio()+"");
            lblInfo.setText("id: " +producto.getIdPro());
            ImgLabel.setText(producto.getImg());
        }
        
    }//GEN-LAST:event_btnSeleccionar1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgLabel;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnImg;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSeleccionar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfprecio;
    // End of variables declaration//GEN-END:variables
}
