/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.Principal.Paneles;

import Tablas.Reserva;
import Pantallas.Principal.CrearReserva;
import Pantallas.Principal.EditarReserva;
import Pantallas.Principal.PantallaPrincipal;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import logica.Main;

/**
 *
 * @author LUIS MIGUEL
 */
public class PanelReservas2 extends javax.swing.JPanel {

    /**
     * Creates new form PanelReservas2
     */
    private  TableRowSorter <DefaultTableModel> sorter;

    public PanelReservas2() {
        initComponents();
        formatearTabla();
        actualizarTabla();
    }
    
    public void formatearTabla(){
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.setColumnIdentifiers(new String[] {"id", "Tipo", "Usuario" ,"Fecha alta", "Fecha baja"});
        TablaReservas.setModel(tabla);
        sorter = new TableRowSorter(tabla);
        
    }
    
    public void actualizarTabla() {
        SwingUtilities.invokeLater(() -> { // es una expreion landa que si no se usa se actualiza en un hilo en el que falla
            DefaultTableModel tabla = (DefaultTableModel) TablaReservas.getModel();
            tabla.setRowCount(0);
            if(PantallaPrincipal.getUser().getAdmin()){
                for (Reserva res : Main.shop.devolverTodasReservas()) {
                    tabla.addRow(res.toArrayString());
                }
            }else{
                for (Reserva res : Main.shop.devolverReservas(PantallaPrincipal.getUser())) {
                    tabla.addRow(res.toArrayString());
                }
            }
        });
        TablaReservas.setRowSorter(sorter);
        List <RowSorter.SortKey> sorkeys = new ArrayList();
        sorkeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
        sorter.setSortKeys(sorkeys);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNueva = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReservas = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Encargos");

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        btnNueva.setBackground(new java.awt.Color(0, 0, 0));
        btnNueva.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNueva.setForeground(new java.awt.Color(255, 255, 0));
        btnNueva.setText("Nueva Reserva");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 0));
        btnBorrar.setText("Borrar Rerva");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 0, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 0));
        btnModificar.setText("Modificar Reserva");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnNueva)
                .addGap(55, 55, 55)
                .addComponent(btnBorrar)
                .addGap(28, 28, 28)
                .addComponent(btnModificar)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNueva)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        TablaReservas.setBackground(new java.awt.Color(0, 0, 0));
        TablaReservas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TablaReservas.setForeground(new java.awt.Color(255, 255, 0));
        TablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaReservas.setAlignmentX(1.0F);
        TablaReservas.setAlignmentY(1.0F);
        TablaReservas.setRowHeight(30);
        TablaReservas.setRowMargin(2);
        jScrollPane1.setViewportView(TablaReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed

        CrearReserva aux = new CrearReserva((Frame) SwingUtilities.getWindowAncestor(this), true);
        aux .setVisible(true);
        actualizarTabla();

    }//GEN-LAST:event_btnNuevaActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int pos = TablaReservas.getSelectedRow();
        int conv = TablaReservas.convertRowIndexToModel(pos);
        if(pos != -1){
            DefaultTableModel tabla = (DefaultTableModel) TablaReservas.getModel();
            int id = Integer.parseInt(TablaReservas.getModel().getValueAt(conv,0).toString());
            Main.shop.eliminarReserva(id);
            actualizarTabla();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int pos = TablaReservas.getSelectedRow();
        int conv = TablaReservas.convertRowIndexToModel(pos);
        Reserva res = null;
        if(pos != -1){
            DefaultTableModel tabla = (DefaultTableModel) TablaReservas.getModel();
            int id = Integer.parseInt(TablaReservas.getModel().getValueAt(conv,0).toString());
            res  = Main.shop.darReserva(id);
            EditarReserva e = new EditarReserva((Frame) SwingUtilities.getWindowAncestor(this), true, res,res.getIdRes());
            e.setVisible(true);
        }
        actualizarTabla();
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaReservas;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
